version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: final-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: final-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/static:/opt/jirarush/resources/static
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge